### ISSUE TITLE
Hey Could you put the link where I can find these

### ISSUE THREAD

**Issue by docharlow** [JonnoFTW/grlcasino#1]
ModuleNotFoundError: No module named 'jsonrpc_requests'

Very sorry. But could you put these files in as well please

**Comment by JonnoFTW** [comment]
You need to run `pip install jsonrpc-requests`

**Comment by docharlow** [comment]
Hey

Thanks for the reply do you have a Discord Possibly where I can contact you?

Much Appreciated

**Comment by JonnoFTW** [comment]
https://discord.gg/U9B6YBH
